board:
    resource: "@BoardBundle/Resources/config/routing.yml"
    prefix:   /

plugins:
    resource: "@PluginsBundle/Resources/config/routing.yml"
    prefix:   /

game:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

#on laisse pour l'exemple
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
