board:
    resource: "@BoardBundle/Resources/config/routing.yml"
    prefix:   /Board/

game:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /Game/

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation

#on laisse pour l'exemple
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
